### ISSUE TITLE
Crash in jq_next -> f_match on master at 3c5b141

### ISSUE THREAD

**Issue by pallas** [stedolan/jq#1803]
At 3c5b141 compiled with CC=afl-gcc and otherwise default configure, the following test case causes a SEGFAULT.
````
capture("(?<a>[a-z]+)-(?-(?<n>[0[[[[[[[-9]+<n>[0[[[[[[[-9]+)")
"xyzzy-14"
{"a":"xyzzy","n":"14"}
````

The backtrace is as follows.
````
0x00007ffff771e97f in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
#0  0x00007ffff771e97f in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffff7f875b3 in onig_error_code_to_str () from /usr/lib64/libonig.so.5
#2  0x000055555561f223 in f_match (jq=<optimized out>, input=..., regex=..., modifiers=..., testmode=...) at src/builtin.c:841
#3  0x000055555556babd in jq_next (jq=0x555555693730) at src/execute.c:855
#4  0x000055555557193e in run_jq_tests (lib_dirs=..., verbose=verbose@entry=0, testdata=testdata@entry=0x555555693500) at src/jq_test.c:146
#5  0x00005555555723b1 in jq_testsuite (libdirs=..., verbose=0, argc=1, argv=0x7fffffffe1c8) at src/jq_test.c:22
#6  0x000055555555e3de in main (argc=3, argv=0x7fffffffe1b8) at src/main.c:520
````

This is a regression from 1.5, where the following error is produced instead.
````
*** Insufficient results for test at line number 3: capture("(?<a>[a-z]+)-(?-(?<n>[0[[[[[[[-9]+<n>[0[[[[[[[-9]+)")
````

jq built off master 3c5b141
oniguruma version 6.9.0
afl version 2.52b
OS: Gentoo on Linux 4.18.6 x86_64

**Comment by pallas** [comment]
It looks like the issue might be that einfo is passed by value, not by pointer here.

**Comment by pallas** [comment]
Valgrind reports
````
==20619== Conditional jump or move depends on uninitialised value(s)
==20619==    at 0x4C3653B: __memcpy_chk (vg_replace_strmem.c:1581)
==20619==    by 0x2FFF1A: memcpy (string_fortified.h:34)
==20619==    by 0x2FFF1A: to_ascii (regerror.c:248)
==20619==    by 0x2FFF1A: onig_error_code_to_str (regerror.c:278)
==20619==    by 0x1B20B8: f_match (builtin.c:841)
==20619==    by 0x127D5E: jq_next (execute.c:855)
==20619==    by 0x12F8FD: run_jq_tests (jq_test.c:146)
==20619==    by 0x1304A0: jq_testsuite (jq_test.c:22)
==20619==    by 0x1182CD: main (main.c:520)
==20619==
==20619== Conditional jump or move depends on uninitialised value(s)
==20619==    at 0x4C36547: __memcpy_chk (vg_replace_strmem.c:1581)
==20619==    by 0x2FFF1A: memcpy (string_fortified.h:34)
==20619==    by 0x2FFF1A: to_ascii (regerror.c:248)
==20619==    by 0x2FFF1A: onig_error_code_to_str (regerror.c:278)
==20619==    by 0x1B20B8: f_match (builtin.c:841)
==20619==    by 0x127D5E: jq_next (execute.c:855)
==20619==    by 0x12F8FD: run_jq_tests (jq_test.c:146)
==20619==    by 0x1304A0: jq_testsuite (jq_test.c:22)
==20619==    by 0x1182CD: main (main.c:520)
==20619==
==20619== Use of uninitialised value of size 8
==20619==    at 0x4C365C8: __memcpy_chk (vg_replace_strmem.c:1581)
==20619==    by 0x2FFF1A: memcpy (string_fortified.h:34)
==20619==    by 0x2FFF1A: to_ascii (regerror.c:248)
==20619==    by 0x2FFF1A: onig_error_code_to_str (regerror.c:278)
==20619==    by 0x1B20B8: f_match (builtin.c:841)
==20619==    by 0x127D5E: jq_next (execute.c:855)
==20619==    by 0x12F8FD: run_jq_tests (jq_test.c:146)
==20619==    by 0x1304A0: jq_testsuite (jq_test.c:22)
==20619==    by 0x1182CD: main (main.c:520)
==20619==
==20619== Invalid read of size 1
==20619==    at 0x4C365C8: __memcpy_chk (vg_replace_strmem.c:1581)
==20619==    by 0x2FFF1A: memcpy (string_fortified.h:34)
==20619==    by 0x2FFF1A: to_ascii (regerror.c:248)
==20619==    by 0x2FFF1A: onig_error_code_to_str (regerror.c:278)
==20619==    by 0x1B20B8: f_match (builtin.c:841)
==20619==    by 0x127D5E: jq_next (execute.c:855)
==20619==    by 0x12F8FD: run_jq_tests (jq_test.c:146)
==20619==    by 0x1304A0: jq_testsuite (jq_test.c:22)
==20619==    by 0x1182CD: main (main.c:520)
==20619==  Address 0x4 is not stack'd, malloc'd or (recently) free'd
==20619==
==20619==
==20619== Process terminating with default action of signal 11 (SIGSEGV)
==20619==  Access not within mapped region at address 0x4
==20619==    at 0x4C365C8: __memcpy_chk (vg_replace_strmem.c:1581)
==20619==    by 0x2FFF1A: memcpy (string_fortified.h:34)
==20619==    by 0x2FFF1A: to_ascii (regerror.c:248)
==20619==    by 0x2FFF1A: onig_error_code_to_str (regerror.c:278)
==20619==    by 0x1B20B8: f_match (builtin.c:841)
==20619==    by 0x127D5E: jq_next (execute.c:855)
==20619==    by 0x12F8FD: run_jq_tests (jq_test.c:146)
==20619==    by 0x1304A0: jq_testsuite (jq_test.c:22)
==20619==    by 0x1182CD: main (main.c:520)
````
which seems to indicate that there is something wrong with einfo itself. Is this object is opaque, I'll close this out and file a bug against oniguruma.
