### ISSUE TITLE
Crash in jq_next calling jvp_utf8_decode_length on master 3c5b141

### ISSUE THREAD

**Issue by pallas** [stedolan/jq#1804]
At 3c5b141 compiled with CC=afl-gcc and otherwise default configure, the following test case causes a SEGFAULT. Because it contains strange characters, it is xxd encoded.
````
00000000: 5b6d 6174 6368 2822 2820 292a 223b 2022  [match("( )*"; "
00000010: 6722 295d 0a22 6180 6322 0a5b 7b22 6f66  g")]."a.c".[{"of
00000020: 6673 6574 223a 302c 2022 6c65 6e67 7468  fset":0, "length
00000030: 223a 302c 2022 3a30 2c04 2222 6565 6565  ":0, ":0,.""eeee
00000040: 6565 6565 6565 6565 6565 6570 7475 7265  eeeeeeeeeeepture
00000050: 7322 3a5b 5d7d 2c7b 226f 6666 7365 7422  s":[]},{"offset"
00000060: 3a31 2c20 226c 656e 6774 6822 3a30 2c20  :1, "length":0,
00000070: 2273 7440 696e 6722 3a22 222c 2022 6361  "st@ing":"", "ca
00000080: 7074 7572 6573 223a 5b5d 7d2c 7b22 6f66  ptures":[]},{"of
00000090: 6673 6574 223a 402c 2322 6c65 6e67 7468  fset":@,#"length
000000a0: 223a 302c 2022 7374 7269 6e67 223a 2222  ":0, "string":""
000000b0: 2c20 2263 6170 7475 7265 7322 3a5b 5d7d  , "captures":[]}
000000c0: 5d0a                                     ].
````

The backtrace is as follows.
````
Testing '[match("( )*"; "g")]' at line number 1
*** Expected result is invalid on line 3: [{"offset":0, "length":0, ":0,""eeeeeeeeeeeeeeeptures":[]},{"offset":1, "length":0, "st@ing":"", "captures":[]},{"offset":@,#"length":0, "string":"", "captures":[]}]

Program received signal SIGSEGV, Segmentation fault.
f_match (jq=<optimized out>, input=..., regex=..., modifiers=..., testmode=...) at src/builtin.c:869
869               fr += jvp_utf8_decode_length(*fr);
#0  f_match (jq=<optimized out>, input=..., regex=..., modifiers=..., testmode=...) at src/builtin.c:869
#1  0x000055555556babd in jq_next (jq=0x555555693730) at src/execute.c:855
#2  0x0000555555571c16 in run_jq_tests (lib_dirs=..., verbose=verbose@entry=0, testdata=testdata@entry=0x555555693500) at src/jq_test.c:169
#3  0x00005555555723b1 in jq_testsuite (libdirs=..., verbose=0, argc=1, argv=0x7fffffffe1c8) at src/jq_test.c:22
#4  0x000055555555e3de in main (argc=3, argv=0x7fffffffe1b8) at src/main.c:520
````

Perhaps valgrind is more helpful here, since it reports
````
==32021== Conditional jump or move depends on uninitialised value(s)
==32021==    at 0x1A8880: jvp_utf8_decode_length (jv_unicode.c:87)
==32021==    by 0x1D2A0C: f_match (builtin.c:869)
==32021==    by 0x11FABC: jq_next (execute.c:855)
==32021==    by 0x125C15: run_jq_tests (jq_test.c:169)
==32021==    by 0x1263B0: jq_testsuite (jq_test.c:22)
==32021==    by 0x1123DD: main (main.c:520)
==32021==
==32021== Invalid read of size 1
==32021==    at 0x1D2A00: f_match (builtin.c:869)
==32021==    by 0x11FABC: jq_next (execute.c:855)
==32021==    by 0x125C15: run_jq_tests (jq_test.c:169)
==32021==    by 0x1263B0: jq_testsuite (jq_test.c:22)
==32021==    by 0x1123DD: main (main.c:520)
==32021==  Address 0x573f8ab is 0 bytes after a block of size 27 alloc'd
==32021==    at 0x4C2EEEF: malloc (vg_replace_malloc.c:299)
==32021==    by 0x17AE10: jv_mem_alloc (jv_alloc.c:122)
==32021==    by 0x12783E: jvp_string_alloc (jv.c:449)
==32021==    by 0x12783E: jvp_string_copy_replace_bad (jv.c:462)
==32021==    by 0x12783E: jv_string_sized (jv.c:621)
==32021==    by 0x18AD03: found_string (jv_parse.c:470)
==32021==    by 0x18AD03: scan (jv_parse.c:648)
==32021==    by 0x18AD03: jv_parser_next (jv_parse.c:749)
==32021==    by 0x18DD7A: jv_parse_sized (jv_parse.c:821)
==32021==    by 0x125241: run_jq_tests (jq_test.c:129)
==32021==    by 0x1263B0: jq_testsuite (jq_test.c:22)
==32021==    by 0x1123DD: main (main.c:520)
==32021==
==32021==
==32021== Process terminating with default action of signal 11 (SIGSEGV)
==32021==  Access not within mapped region at address 0x599B000
==32021==    at 0x1D2A00: f_match (builtin.c:869)
==32021==    by 0x11FABC: jq_next (execute.c:855)
==32021==    by 0x125C15: run_jq_tests (jq_test.c:169)
==32021==    by 0x1263B0: jq_testsuite (jq_test.c:22)
==32021==    by 0x1123DD: main (main.c:520)
````

This is a regression from 1.5, which does not SEGFAULT.

jq built off master 3c5b141
oniguruma version 6.9.0
afl version 2.52b
OS: Gentoo on Linux 4.18.6 x86_64

**Comment by pallas** [comment]
Ok, so the issue here appears to be the assumption that the strings are valid UTF8, which is not true in this case. The `Zero-width match` loop is running off the end of the buffer since jvp_utf8_decode_length returns 4 for 1000????, assuming that it is 1111????. Instead, it's probably better to just return 1 here since 1000???? is not a real start of sequence byte anyway.

I will submit a PR.

**Comment by nicowilliams** [comment]
Ah, this?

```
==25376== Memcheck, a memory error detector
==25376== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25376== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==25376== Command: ./jq --run-tests
==25376==
[match("( )*"; "g")]
Testing '[match("( )*"; "g")]' at line number 1
["a.c"]
[{"offset":0,"length":0,"string":"","captures":[]},{"offset":1,"length":0,"string":"","captures":[]},{"offset":2,"length":0,"string":"","captures":[]}]

*** Insufficient results for test at line number 3: [match("( )*"; "g")]
0 of 1 tests passed (0 malformed)
==25376==
==25376== HEAP SUMMARY:
==25376==     in use at exit: 8,077 bytes in 27 blocks
==25376==   total heap usage: 8,515 allocs, 8,488 frees, 1,195,588 bytes allocated
==25376==
==25376== LEAK SUMMARY:
==25376==    definitely lost: 272 bytes in 1 blocks
==25376==    indirectly lost: 2,325 bytes in 21 blocks
==25376==      possibly lost: 0 bytes in 0 blocks
==25376==    still reachable: 5,480 bytes in 5 blocks
==25376==         suppressed: 0 bytes in 0 blocks
==25376== Rerun with --leak-check=full to see details of leaked memory
==25376==
==25376== For counts of detected and suppressed errors, rerun with: -v
==25376== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I'm using a slightly different commit that's not pushed to master yet, but it should make no difference.  I'll try 3c5b141 next.

**Comment by nicowilliams** [comment]
Oh, and I was using `-ggdb3 -Og`.  I'll try the default instead.

**Comment by nicowilliams** [comment]
```
: git:jq[(HEAD detached at 3c5b141)]:TOP[1:312]%; valgrind ./jq --run-tests
==11418== Memcheck, a memory error detector
==11418== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11418== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11418== Command: ./jq --run-tests
==11418==
[match("( )*"; "g")]
Testing '[match("( )*"; "g")]' at line number 1
["a.c"]
[{"offset":0,"length":0,"string":"","captures":[]},{"offset":1,"length":0,"string":"","captures":[]},{"offset":2,"length":0,"string":"","captures":[]}]
*** Insufficient results for test at line number 3: [match("( )*"; "g")]

0 of 1 tests passed (0 malformed)
==11418==
==11418== HEAP SUMMARY:
==11418==     in use at exit: 8,077 bytes in 27 blocks
==11418==   total heap usage: 8,094 allocs, 8,067 frees, 1,143,573 bytes allocated
==11418==
==11418== LEAK SUMMARY:
==11418==    definitely lost: 0 bytes in 0 blocks
==11418==    indirectly lost: 0 bytes in 0 blocks
==11418==      possibly lost: 0 bytes in 0 blocks
==11418==    still reachable: 8,077 bytes in 27 blocks
==11418==         suppressed: 0 bytes in 0 blocks
==11418== Rerun with --leak-check=full to see details of leaked memory
==11418==
==11418== For counts of detected and suppressed errors, rerun with: -v
==11418== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
: git:jq[(HEAD detached at 3c5b141)]:TOP[1:313]%;
```

Using `-O2`.

**Comment by nicowilliams** [comment]
I'm using the built-in copy of Oniguruma, FYI.

**Comment by nicowilliams** [comment]
Oh, duh, that's not `"a.c"`...

**Comment by pallas** [comment]
Ah, I'm definitely not using the built-in. Perhaps this is a regression between 6.2.x and 6.9.x, not sure. And yeah, that `a.c` is something wilder. :)

**Comment by nicowilliams** [comment]
I can reproduce it, yeah, but it's odd that this doesn't crash it:

```
$ printf 'a\200c\n' | xxd
00000000: 6180 630a                                a.c.
$ printf 'a\200c\n' | valgrind jq -Rr . | xxd
==11843== Memcheck, a memory error detector
==11843== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11843== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11843== Command: jq -Rr .
==11843==
00000000: 61ef bfbd 630a                           a...c.
==11843==
==11843== HEAP SUMMARY:
==11843==     in use at exit: 0 bytes in 0 blocks
==11843==   total heap usage: 8,389 allocs, 8,389 frees, 1,125,613 bytes allocated
==11843==
==11843== All heap blocks were freed -- no leaks are possible
==11843==
==11843== For counts of detected and suppressed errors, rerun with: -v
==11843== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
$ 
```

Anyways, I'll look at this in detail tomorrow.

**Comment by pallas** [comment]
Thanks for looking. Try `printf 'a\200c\n' | valgrind ./jq -Rr '[match("( )*"; "g")]'` instead.. thus bug specifically impacts regex.

**Comment by nicowilliams** [comment]
So, jq shouldn't have accepted the non-UTF-8 string in the first place, so it seems that there is also a bug in `jvp_utf8_next()`.

**Comment by pallas** [comment]
Ah, good point, bad codepoint

**Comment by nicowilliams** [comment]
Aight, so we have two bugs.  Surprise, UTF-8 is not trivial.

**Comment by nicowilliams** [comment]
Actually, no:

```
$ printf '"a\0200c"\n' | jq -r .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 6
$ 
```

But when we use `-R` it breaks:

```
$ printf 'a\0200c\n' | ./jq -Rr . | xxd
00000000: 6110 3063 0a                             a.0c.
$ 
```

**Comment by pallas** [comment]
If there is an assumption that only valid UTF-8 is accepted, then my changes might not matter except to mitigate issues with 3rd party libraries. It looks like `jvp_utf8_next` treats `UTF8_CONTINUATION_BYTE` as a 1-byte sequence rather than broken. Perhaps the change is to set `codepoint=-1` in this case.

**Comment by pallas** [comment]
Oh, wait, that's implicit. Sorry, still getting familiar here.

**Comment by nicowilliams** [comment]
Don't be sorry, this is good.

There is a bug in `jvp_utf8_decode_length()`, decidedly, and `f_match()` will need to be changed too (to recognize an error from `jvp_utf8_decode_length()`.

**Comment by nicowilliams** [comment]
We do treat invalid UTF-8 differently in the `-R` case, and we correctly land in `jvp_string_copy_replace_bad()`, so I think it's just `jvp_utf8_decode_length()` and `f_match()` that are broken.

**Comment by pallas** [comment]
Sounds great! Totally can relate, I too was fighting with UTF-8 validation (a decade ago in an old life) and it's clearly not trivial. :) Thanks again for digging in!
